
    create table articoli (
        categoria_id integer not null,
        genere_id integer not null,
        id integer generated by default as identity,
        marca_id integer not null,
        prezzo float(53),
        taglia_scarpe integer check ((taglia_scarpe>=30) and (taglia_scarpe<=50)),
        descrizione varchar(255),
        nome varchar(255),
        taglia_indumento varchar(255),
        primary key (id)
    );

    create table carrello (
        id integer generated by default as identity,
        utente_id integer not null unique,
        primary key (id)
    );

    create table carrello_item (
        articolo_id integer not null,
        carrello_id integer not null,
        prezzo_totale float(53),
        quantita integer,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table categoria (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table genere (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table marca (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table taglia_indumento (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table utenti (
        id integer generated by default as identity,
        cognome varchar(255),
        email varchar(255),
        nome varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','USER')),
        username varchar(255),
        primary key (id)
    );

    alter table if exists articoli 
       add constraint FK5d2x4xop5vq9mjsbohm65ual6 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists articoli 
       add constraint FKbqwhwigu6vu9am118tp342y9 
       foreign key (genere_id) 
       references genere;

    alter table if exists articoli 
       add constraint FKkop5x64hfqpj13e6hqe3o0qn3 
       foreign key (marca_id) 
       references marca;

    alter table if exists carrello 
       add constraint FKn2e1cil2mfpgxyn5gn7umt0lj 
       foreign key (utente_id) 
       references utenti;

    alter table if exists carrello_item 
       add constraint FK49hpbsabryedafqp4diqraxlq 
       foreign key (articolo_id) 
       references articoli;

    alter table if exists carrello_item 
       add constraint FK2uy8v67ws6bc0qctdgrhg011d 
       foreign key (carrello_id) 
       references carrello;
