
    create table carrello (
        id integer generated by default as identity,
        utente_id integer not null unique,
        primary key (id)
    );

    create table utenti (
        id integer generated by default as identity,
        cognome varchar(255),
        email varchar(255),
        nome varchar(255),
        paolo varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','USER')),
        username varchar(255),
        primary key (id)
    );

    alter table if exists carrello 
       add constraint FKn2e1cil2mfpgxyn5gn7umt0lj 
       foreign key (utente_id) 
       references utenti;
